# =========================================================
# PROD OVERRIDES
# =========================================================
jwt.expiration=70d

tiendanube.webhook-registration.enabled=${TIENDANUBE_WEBHOOK_REGISTRATION_ENABLED}
tiendanube.reconciliation.enabled=${TIENDANUBE_RECONCILIATION_ENABLED}
tiendanube.reconciliation.auto-repair-enabled=${TIENDANUBE_RECONCILIATION_AUTO_REPAIR_ENABLED}
