# =========================================================
# DEV OVERRIDES
# =========================================================
jwt.expiration=2h

tiendanube.webhook-registration.enabled=${TIENDANUBE_WEBHOOK_REGISTRATION_ENABLED}
tiendanube.reconciliation.enabled=${TIENDANUBE_RECONCILIATION_ENABLED}
tiendanube.reconciliation.auto-repair-enabled=${TIENDANUBE_RECONCILIATION_AUTO_REPAIR_ENABLED}
