CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE publishers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_publishers_name UNIQUE (name)
);

CREATE TABLE authors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_authors_name UNIQUE (name)
);

CREATE TABLE books
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn                    VARCHAR(20)  NOT NULL,
    title                   VARCHAR(255) NOT NULL,
    subtitle                VARCHAR(255),
    description             TEXT,
    language                VARCHAR(50),
    page_count              INTEGER,
    publication_date        DATE,
    cover_url               VARCHAR(1000),
    retail_price            NUMERIC(12, 2),
    retail_price_updated_at DATE,
    source                  VARCHAR(50)  NOT NULL DEFAULT 'MANUAL',
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    publisher_id            BIGINT,
    created_at              TIMESTAMP WITH TIME ZONE,
    updated_at              TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_books_isbn UNIQUE (isbn),

    CONSTRAINT fk_books_publishers
        FOREIGN KEY (publisher_id)
            REFERENCES publishers (id),

    CONSTRAINT chk_books_retail_price_non_negative
        CHECK (retail_price IS NULL OR retail_price >= 0),

    CONSTRAINT chk_books_source
        CHECK (source IN ('MANUAL', 'EXTERNAL_METADATA', 'EDITORIAL_PRICE_LIST'))
);

CREATE TABLE book_authors
(
    book_id   BIGINT NOT NULL,
    author_id BIGINT NOT NULL,

    CONSTRAINT pk_book_authors PRIMARY KEY (book_id, author_id),

    CONSTRAINT fk_book_authors_book
        FOREIGN KEY (book_id)
            REFERENCES books (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_book_authors_author
        FOREIGN KEY (author_id)
            REFERENCES authors (id)
);

CREATE TABLE inventory
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id       BIGINT  NOT NULL,
    stock         INTEGER NOT NULL DEFAULT 0,
    minimum_stock INTEGER NOT NULL DEFAULT 0,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE,
    updated_at    TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_inventory_book_id UNIQUE (book_id),

    CONSTRAINT fk_inventory_books
        FOREIGN KEY (book_id)
            REFERENCES books (id),

    CONSTRAINT chk_inventory_stock_non_negative
        CHECK (stock >= 0),

    CONSTRAINT chk_inventory_minimum_stock_non_negative
        CHECK (minimum_stock >= 0)
);

CREATE INDEX idx_books_title_trgm
    ON books USING gin (title gin_trgm_ops);

CREATE INDEX idx_books_isbn
    ON books (isbn);

CREATE INDEX idx_books_publisher_id
    ON books (publisher_id);

CREATE INDEX idx_authors_name_trgm
    ON authors USING gin (name gin_trgm_ops);

CREATE INDEX idx_publishers_name_trgm
    ON publishers USING gin (name gin_trgm_ops);

CREATE INDEX idx_book_authors_author_id
    ON book_authors (author_id);

CREATE INDEX idx_inventory_book_id
    ON inventory (book_id);

CREATE INDEX idx_inventory_active
    ON inventory (active);

CREATE TABLE inventory_movements
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT      NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    quantity     INTEGER     NOT NULL,
    stock_before INTEGER     NOT NULL,
    stock_after  INTEGER     NOT NULL,
    reason       VARCHAR(255),
    created_at   TIMESTAMP WITH TIME ZONE,
    updated_at   TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_inventory_movements_inventory
        FOREIGN KEY (inventory_id)
            REFERENCES inventory (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_inventory_movements_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_inventory_movements_type
        CHECK (movement_type IN (
                        'INITIAL_STOCK',
                        'ENTRY',
                        'SALE',
                        'ADJUSTMENT'
            ))
);

CREATE INDEX idx_inventory_movements_inventory
    ON inventory_movements (inventory_id);

CREATE INDEX idx_inventory_movements_type
    ON inventory_movements (movement_type);

CREATE INDEX idx_inventory_movements_created_at
    ON inventory_movements (created_at DESC);