CREATE TABLE publishers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE authors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn             VARCHAR(20)  NOT NULL UNIQUE,
    title            VARCHAR(255) NOT NULL,
    subtitle         VARCHAR(255),
    description      TEXT,
    language         VARCHAR(50),
    page_count       INTEGER,
    publication_date DATE,
    cover_url        VARCHAR(1000),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    publisher_id     BIGINT,
    created_at       TIMESTAMP WITH TIME ZONE,
    updated_at       TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_books_publishers
        FOREIGN KEY (publisher_id)
            REFERENCES publishers (id)
);

CREATE TABLE book_authors
(
    book_id   BIGINT NOT NULL,
    author_id BIGINT NOT NULL,

    PRIMARY KEY (book_id, author_id),

    CONSTRAINT fk_book_authors_book
        FOREIGN KEY (book_id)
            REFERENCES books (id),

    CONSTRAINT fk_book_authors_author
        FOREIGN KEY (author_id)
            REFERENCES authors (id)
);