CREATE TABLE inventory
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT         NOT NULL UNIQUE,
    stock      INTEGER        NOT NULL DEFAULT 0,
    cost_price NUMERIC(12, 2) NOT NULL,
    sale_price NUMERIC(12, 2) NOT NULL,
    active     BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_inventory_books
        FOREIGN KEY (book_id)
            REFERENCES books (id),

    CONSTRAINT chk_inventory_stock_non_negative
        CHECK (stock >= 0),

    CONSTRAINT chk_inventory_cost_price_non_negative
        CHECK (cost_price >= 0),

    CONSTRAINT chk_inventory_sale_price_non_negative
        CHECK (sale_price >= 0)
);

CREATE TABLE inventory_movements
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT      NOT NULL,
    type         VARCHAR(50) NOT NULL,
    quantity     INTEGER     NOT NULL,
    cost_price   NUMERIC(12, 2),
    sale_price   NUMERIC(12, 2),
    reason       VARCHAR(255),
    created_at   TIMESTAMP WITH TIME ZONE,
    updated_at   TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_inventory_movements_inventory
        FOREIGN KEY (inventory_id)
            REFERENCES inventory (id),

    CONSTRAINT chk_inventory_movements_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_inventory_movements_type
        CHECK (type IN ('PURCHASE', 'SALE', 'ADJUSTMENT'))
);

CREATE INDEX idx_inventory_movements_inventory_id
    ON inventory_movements (inventory_id);