-- Cola durable de operaciones salientes hacia Tiendanube.
-- Los jobs sobreviven reinicios/deploys y se reclaman con FOR UPDATE SKIP LOCKED.

CREATE TABLE tiendanube_sync_jobs
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookstore_id          BIGINT      NOT NULL,
    store_id              BIGINT      NOT NULL,
    inventory_id          BIGINT      NOT NULL,
    type                  VARCHAR(40) NOT NULL,
    status                VARCHAR(30) NOT NULL,
    source                VARCHAR(30) NOT NULL,
    attempt_count         INTEGER     NOT NULL DEFAULT 0,
    max_attempts          INTEGER     NOT NULL DEFAULT 7,
    next_attempt_at       TIMESTAMPTZ NOT NULL,
    processing_started_at TIMESTAMPTZ,
    lease_until           TIMESTAMPTZ,
    processing_token      UUID,
    completed_at          TIMESTAMPTZ,
    last_error_type       VARCHAR(120),
    last_error_message    TEXT,
    last_http_status      INTEGER,
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_tiendanube_sync_jobs_bookstore
        FOREIGN KEY (bookstore_id) REFERENCES bookstores (id) ON DELETE CASCADE,

    CONSTRAINT fk_tiendanube_sync_jobs_store
        FOREIGN KEY (store_id) REFERENCES tiendanube_stores (store_id) ON DELETE CASCADE,

    CONSTRAINT fk_tiendanube_sync_jobs_inventory
        FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE,

    CONSTRAINT ck_tiendanube_sync_jobs_type
        CHECK (type IN ('PUBLISH', 'SYNC_STOCK', 'SYNC_PRICE', 'SYNC_PUBLICATION', 'DELETE_PUBLICATION')),

    CONSTRAINT ck_tiendanube_sync_jobs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY_WAIT', 'COMPLETED', 'FAILED', 'BLOCKED', 'CANCELLED')),

    CONSTRAINT ck_tiendanube_sync_jobs_source
        CHECK (source IN ('AUTOMATIC', 'MANUAL', 'BULK', 'RECONCILIATION')),

    CONSTRAINT ck_tiendanube_sync_jobs_attempt_count
        CHECK (attempt_count >= 0),

    CONSTRAINT ck_tiendanube_sync_jobs_max_attempts
        CHECK (max_attempts >= 1),

    CONSTRAINT ck_tiendanube_sync_jobs_processing_lease
        CHECK (
            (status = 'PROCESSING' AND processing_started_at IS NOT NULL AND lease_until IS NOT NULL AND
             processing_token IS NOT NULL)
                OR
            (status <> 'PROCESSING' AND processing_started_at IS NULL AND lease_until IS NULL AND
             processing_token IS NULL)
            )
);

CREATE TABLE tiendanube_sync_attempts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id           BIGINT      NOT NULL,
    attempt_number   INTEGER     NOT NULL,
    processing_token UUID        NOT NULL,
    status           VARCHAR(30) NOT NULL,
    started_at       TIMESTAMPTZ NOT NULL,
    completed_at     TIMESTAMPTZ,
    http_status      INTEGER,
    error_type       VARCHAR(120),
    error_message    TEXT,

    CONSTRAINT fk_tiendanube_sync_attempts_job
        FOREIGN KEY (job_id) REFERENCES tiendanube_sync_jobs (id) ON DELETE CASCADE,

    CONSTRAINT uk_tiendanube_sync_attempt_job_number
        UNIQUE (job_id, attempt_number),

    CONSTRAINT ck_tiendanube_sync_attempts_number
        CHECK (attempt_number >= 1),

    CONSTRAINT ck_tiendanube_sync_attempts_status
        CHECK (status IN ('PROCESSING', 'COMPLETED', 'RETRY_SCHEDULED', 'FAILED', 'BLOCKED', 'STALE'))
);

-- Un mismo inventario/operación sólo necesita un job pendiente. Si hay uno PROCESSING,
-- puede existir además un PENDING para capturar un cambio ocurrido mientras el primero estaba en vuelo.
CREATE UNIQUE INDEX uk_tiendanube_sync_jobs_pending_inventory_type
    ON tiendanube_sync_jobs (inventory_id, type)
    WHERE status IN ('PENDING', 'RETRY_WAIT');

CREATE INDEX idx_tiendanube_sync_jobs_claim
    ON tiendanube_sync_jobs (status, next_attempt_at, lease_until, id)
    WHERE status IN ('PENDING', 'RETRY_WAIT', 'PROCESSING');

CREATE INDEX idx_tiendanube_sync_jobs_inventory
    ON tiendanube_sync_jobs (inventory_id, created_at DESC);

CREATE INDEX idx_tiendanube_sync_jobs_store
    ON tiendanube_sync_jobs (store_id, status, created_at DESC);

CREATE INDEX idx_tiendanube_sync_attempts_job
    ON tiendanube_sync_attempts (job_id, started_at DESC);
