-- Operaciones masivas de Tiendanube.
-- La selección se materializa en items durables y un dispatcher local los convierte
-- gradualmente en jobs de la cola saliente existente o en acciones locales idempotentes.

CREATE TABLE tiendanube_bulk_operations
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookstore_id          BIGINT      NOT NULL,
    tiendanube_store_id   BIGINT      NOT NULL,
    store_id              BIGINT      NOT NULL,
    action                VARCHAR(40) NOT NULL,
    selection_type        VARCHAR(20) NOT NULL,
    selection_description TEXT,
    cancel_requested_at   TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_tiendanube_bulk_operations_bookstore
        FOREIGN KEY (bookstore_id) REFERENCES bookstores (id) ON DELETE CASCADE,

    CONSTRAINT fk_tiendanube_bulk_operations_store
        FOREIGN KEY (tiendanube_store_id) REFERENCES tiendanube_stores (id) ON DELETE CASCADE,

    CONSTRAINT ck_tiendanube_bulk_operations_action
        CHECK (action IN (
            'PUBLISH',
            'SYNC_PUBLICATION',
            'SYNC_STOCK',
            'SYNC_PRICE',
            'DELETE_PUBLICATION',
            'UNLINK',
            'ENABLE_PRICE_SYNC',
            'DISABLE_PRICE_SYNC'
        )),

    CONSTRAINT ck_tiendanube_bulk_operations_selection_type
        CHECK (selection_type IN ('IDS', 'FILTER'))
);

CREATE TABLE tiendanube_bulk_operation_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id      BIGINT       NOT NULL,
    inventory_id      BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    job_id            BIGINT,
    skip_reason       VARCHAR(120),
    skip_message      TEXT,
    dispatched_at     TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_tiendanube_bulk_items_operation
        FOREIGN KEY (operation_id) REFERENCES tiendanube_bulk_operations (id) ON DELETE CASCADE,

    CONSTRAINT fk_tiendanube_bulk_items_inventory
        FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE,

    -- Mantener el job mientras exista el historial de la operación. La limpieza histórica
    -- deberá borrar primero operaciones/items y después jobs.
    CONSTRAINT fk_tiendanube_bulk_items_job
        FOREIGN KEY (job_id) REFERENCES tiendanube_sync_jobs (id) ON DELETE RESTRICT,

    CONSTRAINT uk_tiendanube_bulk_items_operation_inventory
        UNIQUE (operation_id, inventory_id),

    CONSTRAINT ck_tiendanube_bulk_items_status
        CHECK (status IN ('PENDING', 'QUEUED', 'COMPLETED', 'SKIPPED', 'CANCELLED')),

    CONSTRAINT ck_tiendanube_bulk_items_result
        CHECK (
            (status = 'QUEUED' AND job_id IS NOT NULL AND skip_reason IS NULL AND completed_at IS NULL)
            OR
            (status = 'COMPLETED' AND job_id IS NULL AND skip_reason IS NULL AND completed_at IS NOT NULL)
            OR
            (status = 'SKIPPED' AND job_id IS NULL AND skip_reason IS NOT NULL)
            OR
            (status IN ('PENDING', 'CANCELLED') AND job_id IS NULL AND completed_at IS NULL)
        )
);

CREATE INDEX idx_tiendanube_bulk_operations_bookstore_created
    ON tiendanube_bulk_operations (bookstore_id, created_at DESC);

CREATE INDEX idx_tiendanube_bulk_operations_store_created
    ON tiendanube_bulk_operations (tiendanube_store_id, created_at DESC);

CREATE INDEX idx_tiendanube_bulk_items_dispatch
    ON tiendanube_bulk_operation_items (status, id)
    WHERE status = 'PENDING';

CREATE INDEX idx_tiendanube_bulk_items_operation
    ON tiendanube_bulk_operation_items (operation_id, id);

CREATE INDEX idx_tiendanube_bulk_items_job
    ON tiendanube_bulk_operation_items (job_id)
    WHERE job_id IS NOT NULL;
