CREATE TABLE tiendanube_webhook_events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiendanube_store_id   BIGINT,
    store_id              BIGINT       NOT NULL,
    event                 VARCHAR(100) NOT NULL,
    resource_id           BIGINT,
    payload               JSONB        NOT NULL,
    status                VARCHAR(32)  NOT NULL,
    attempt_count         INTEGER      NOT NULL DEFAULT 0,
    max_attempts          INTEGER      NOT NULL DEFAULT 12,
    next_attempt_at       TIMESTAMPTZ  NOT NULL,
    processing_token      UUID,
    processing_started_at TIMESTAMPTZ,
    lease_expires_at      TIMESTAMPTZ,
    completed_at          TIMESTAMPTZ,
    last_error_type       VARCHAR(100),
    last_error_message    TEXT,
    received_at           TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_tiendanube_webhook_events_store
        FOREIGN KEY (tiendanube_store_id)
            REFERENCES tiendanube_stores (id)
            ON DELETE SET NULL,

    CONSTRAINT ck_tiendanube_webhook_events_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY_WAIT', 'COMPLETED', 'FAILED', 'IGNORED')),

    CONSTRAINT ck_tiendanube_webhook_events_attempt_count
        CHECK (attempt_count >= 0),

    CONSTRAINT ck_tiendanube_webhook_events_max_attempts
        CHECK (max_attempts > 0)
);

CREATE INDEX idx_tiendanube_webhook_events_claim
    ON tiendanube_webhook_events (next_attempt_at, received_at, id)
    WHERE status IN ('PENDING', 'RETRY_WAIT');

CREATE INDEX idx_tiendanube_webhook_events_expired_lease
    ON tiendanube_webhook_events (lease_expires_at, id)
    WHERE status = 'PROCESSING';

CREATE INDEX idx_tiendanube_webhook_events_resource
    ON tiendanube_webhook_events (store_id, resource_id, event);

CREATE INDEX idx_tiendanube_webhook_events_received
    ON tiendanube_webhook_events (store_id, received_at DESC, id DESC);
