CREATE TABLE tiendanube_reconciliation_runs
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookstore_id          BIGINT      NOT NULL,
    tiendanube_store_id   BIGINT      NOT NULL,
    store_id              BIGINT      NOT NULL,
    source                VARCHAR(30) NOT NULL,
    status                VARCHAR(30) NOT NULL,
    linked_count          INTEGER     NOT NULL DEFAULT 0,
    checked_count         INTEGER     NOT NULL DEFAULT 0,
    issue_count           INTEGER     NOT NULL DEFAULT 0,
    last_error_type       VARCHAR(100),
    last_error_message    TEXT,
    processing_token      UUID,
    processing_started_at TIMESTAMPTZ,
    lease_expires_at      TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at          TIMESTAMPTZ,

    CONSTRAINT fk_tiendanube_reconciliation_runs_bookstore
        FOREIGN KEY (bookstore_id) REFERENCES bookstores (id),

    CONSTRAINT fk_tiendanube_reconciliation_runs_store
        FOREIGN KEY (tiendanube_store_id) REFERENCES tiendanube_stores (id),

    CONSTRAINT ck_tiendanube_reconciliation_runs_source
        CHECK (source IN ('MANUAL', 'SCHEDULED')),

    CONSTRAINT ck_tiendanube_reconciliation_runs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),

    CONSTRAINT ck_tiendanube_reconciliation_runs_counts
        CHECK (linked_count >= 0 AND checked_count >= 0 AND issue_count >= 0)
);

CREATE UNIQUE INDEX uk_tiendanube_reconciliation_runs_active_store
    ON tiendanube_reconciliation_runs (tiendanube_store_id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE INDEX idx_tiendanube_reconciliation_runs_claim
    ON tiendanube_reconciliation_runs (status, lease_expires_at, created_at, id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE INDEX idx_tiendanube_reconciliation_runs_bookstore
    ON tiendanube_reconciliation_runs (bookstore_id, created_at DESC, id DESC);

CREATE TABLE tiendanube_reconciliation_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       BIGINT      NOT NULL,
    inventory_id BIGINT      NOT NULL,
    link_id      BIGINT      NOT NULL,
    product_id   BIGINT      NOT NULL,
    variant_id   BIGINT      NOT NULL,
    issue_type   VARCHAR(50) NOT NULL,
    local_stock  INTEGER,
    remote_stock INTEGER,
    local_price  NUMERIC(12, 2),
    remote_price NUMERIC(12, 2),
    message      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tiendanube_reconciliation_items_run
        FOREIGN KEY (run_id)
            REFERENCES tiendanube_reconciliation_runs (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_tiendanube_reconciliation_items_inventory
        FOREIGN KEY (inventory_id) REFERENCES inventory (id),

    CONSTRAINT fk_tiendanube_reconciliation_items_link
        FOREIGN KEY (link_id) REFERENCES tiendanube_product_links (id),

    CONSTRAINT ck_tiendanube_reconciliation_items_issue_type
        CHECK (issue_type IN (
                              'REMOTE_PRODUCT_MISSING',
                              'REMOTE_VARIANT_MISSING',
                              'STOCK_MISMATCH',
                              'PRICE_MISMATCH'
            )),

    CONSTRAINT uk_tiendanube_reconciliation_items_issue
        UNIQUE (run_id, inventory_id, issue_type)
);

CREATE INDEX idx_tiendanube_reconciliation_items_run
    ON tiendanube_reconciliation_items (run_id, id);
