-- =========================================================
-- CATÁLOGO PENDIENTE
-- =========================================================

CREATE TABLE catalog_candidates
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn_10                    VARCHAR(10),
    isbn_13                    VARCHAR(13)  NOT NULL,
    status                     VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    resolved_book_id           BIGINT,
    first_seen_by_bookstore_id BIGINT       NOT NULL,
    resolved_by_user_id        BIGINT,
    resolved_at                TIMESTAMPTZ,
    created_at                 TIMESTAMPTZ  NOT NULL,
    updated_at                 TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_catalog_candidates_isbn13 UNIQUE (isbn_13),

    CONSTRAINT fk_catalog_candidates_resolved_book
        FOREIGN KEY (resolved_book_id) REFERENCES books (id),

    CONSTRAINT fk_catalog_candidates_first_bookstore
        FOREIGN KEY (first_seen_by_bookstore_id) REFERENCES bookstores (id),

    CONSTRAINT fk_catalog_candidates_resolved_user
        FOREIGN KEY (resolved_by_user_id) REFERENCES users (id),

    CONSTRAINT ck_catalog_candidates_status
        CHECK (status IN ('PENDING', 'RESOLVED', 'REJECTED')),

    CONSTRAINT ck_catalog_candidates_resolution
        CHECK (
            (status = 'RESOLVED' AND resolved_book_id IS NOT NULL AND resolved_at IS NOT NULL)
            OR
            (status <> 'RESOLVED')
        )
);

CREATE INDEX idx_catalog_candidates_status_created
    ON catalog_candidates (status, created_at, id);

-- =========================================================
-- SESIONES DE CONTEO
-- =========================================================

CREATE TABLE inventory_count_sessions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookstore_id       BIGINT       NOT NULL,
    created_by_user_id BIGINT       NOT NULL,
    mode               VARCHAR(20)  NOT NULL,
    purpose            VARCHAR(30)  NOT NULL,
    status             VARCHAR(30)  NOT NULL DEFAULT 'OPEN',
    condition          VARCHAR(20)  NOT NULL DEFAULT 'NEW',
    baseline_at        TIMESTAMPTZ  NOT NULL,
    reviewed_at        TIMESTAMPTZ,
    applied_at         TIMESTAMPTZ,
    reverted_at        TIMESTAMPTZ,
    notes              VARCHAR(500),
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_inventory_count_sessions_bookstore
        FOREIGN KEY (bookstore_id) REFERENCES bookstores (id),

    CONSTRAINT fk_inventory_count_sessions_user
        FOREIGN KEY (created_by_user_id) REFERENCES users (id),

    CONSTRAINT ck_inventory_count_sessions_mode
        CHECK (mode IN ('ADDITIVE', 'ABSOLUTE')),

    CONSTRAINT ck_inventory_count_sessions_purpose
        CHECK (purpose IN ('INITIAL_LOAD', 'DELIVERY', 'RECONCILIATION', 'AUDIT')),

    CONSTRAINT ck_inventory_count_sessions_status
        CHECK (status IN ('OPEN', 'REVIEW', 'APPLIED', 'APPLIED_WITH_PENDING', 'REVERTED', 'CANCELLED')),

    CONSTRAINT ck_inventory_count_sessions_condition
        CHECK (condition IN ('NEW', 'USED'))
);

CREATE INDEX idx_inventory_count_sessions_bookstore_created
    ON inventory_count_sessions (bookstore_id, created_at DESC, id DESC);

CREATE UNIQUE INDEX uk_inventory_count_sessions_open_absolute
    ON inventory_count_sessions (bookstore_id, condition)
    WHERE mode = 'ABSOLUTE' AND status IN ('OPEN', 'REVIEW');

-- =========================================================
-- ÍTEMS ESCANEADOS
-- =========================================================

CREATE TABLE inventory_count_items
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id            BIGINT         NOT NULL,
    raw_identifier        VARCHAR(100)   NOT NULL,
    normalized_identifier VARCHAR(100)   NOT NULL,
    isbn_10               VARCHAR(10),
    isbn_13               VARCHAR(13),
    book_id               BIGINT,
    catalog_candidate_id  BIGINT,
    quantity              INTEGER        NOT NULL DEFAULT 1,
    status                VARCHAR(30)    NOT NULL,
    sale_price_override   NUMERIC(12, 2),
    first_scanned_at      TIMESTAMPTZ    NOT NULL,
    last_scanned_at       TIMESTAMPTZ    NOT NULL,
    applied_at            TIMESTAMPTZ,
    created_at            TIMESTAMPTZ    NOT NULL,
    updated_at            TIMESTAMPTZ    NOT NULL,

    CONSTRAINT fk_inventory_count_items_session
        FOREIGN KEY (session_id) REFERENCES inventory_count_sessions (id) ON DELETE CASCADE,

    CONSTRAINT fk_inventory_count_items_book
        FOREIGN KEY (book_id) REFERENCES books (id),

    CONSTRAINT fk_inventory_count_items_candidate
        FOREIGN KEY (catalog_candidate_id) REFERENCES catalog_candidates (id),

    CONSTRAINT uk_inventory_count_items_identifier
        UNIQUE (session_id, normalized_identifier),

    CONSTRAINT ck_inventory_count_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_inventory_count_items_price
        CHECK (sale_price_override IS NULL OR sale_price_override > 0),

    CONSTRAINT ck_inventory_count_items_status
        CHECK (status IN ('RESOLVED', 'PENDING_CATALOG', 'PENDING_PRICE', 'INVALID_IDENTIFIER', 'SUPERSEDED')),

    CONSTRAINT ck_inventory_count_items_resolution
        CHECK (
            (status IN ('RESOLVED', 'PENDING_PRICE') AND book_id IS NOT NULL)
            OR
            (status = 'PENDING_CATALOG' AND catalog_candidate_id IS NOT NULL)
            OR
            (status = 'INVALID_IDENTIFIER' AND book_id IS NULL AND catalog_candidate_id IS NULL)
            OR
            (status = 'SUPERSEDED' AND book_id IS NOT NULL)
        )
);

CREATE INDEX idx_inventory_count_items_session_last_scan
    ON inventory_count_items (session_id, last_scanned_at DESC, id DESC);

CREATE INDEX idx_inventory_count_items_candidate
    ON inventory_count_items (catalog_candidate_id)
    WHERE catalog_candidate_id IS NOT NULL;

CREATE INDEX idx_inventory_count_items_pending
    ON inventory_count_items (session_id, status, id)
    WHERE applied_at IS NULL;

-- =========================================================
-- SNAPSHOT / RESULTADO DE CONTEO
-- =========================================================

CREATE TABLE inventory_count_results
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id               BIGINT      NOT NULL,
    book_id                  BIGINT      NOT NULL,
    inventory_id             BIGINT,
    baseline                 BOOLEAN     NOT NULL DEFAULT FALSE,
    inventory_existed_before BOOLEAN     NOT NULL DEFAULT FALSE,
    previous_active          BOOLEAN     NOT NULL DEFAULT FALSE,
    previous_quantity        INTEGER     NOT NULL DEFAULT 0,
    counted_quantity         INTEGER,
    applied_delta            INTEGER     NOT NULL DEFAULT 0,
    resulting_quantity       INTEGER,
    resulting_active         BOOLEAN,
    difference_type          VARCHAR(20),
    applied_at               TIMESTAMPTZ,
    reverted_at              TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL,
    updated_at               TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_inventory_count_results_session
        FOREIGN KEY (session_id) REFERENCES inventory_count_sessions (id) ON DELETE CASCADE,

    CONSTRAINT fk_inventory_count_results_book
        FOREIGN KEY (book_id) REFERENCES books (id),

    CONSTRAINT fk_inventory_count_results_inventory
        FOREIGN KEY (inventory_id) REFERENCES inventory (id),

    CONSTRAINT uk_inventory_count_results_session_book
        UNIQUE (session_id, book_id),

    CONSTRAINT ck_inventory_count_results_quantities
        CHECK (
            previous_quantity >= 0
            AND (counted_quantity IS NULL OR counted_quantity >= 0)
            AND (resulting_quantity IS NULL OR resulting_quantity >= 0)
        ),

    CONSTRAINT ck_inventory_count_results_difference
        CHECK (difference_type IS NULL OR difference_type IN ('MATCH', 'SURPLUS', 'SHORTAGE', 'MISSING', 'NEW', 'ADDED'))
);

CREATE INDEX idx_inventory_count_results_session_difference
    ON inventory_count_results (session_id, difference_type, id);

CREATE INDEX idx_inventory_count_results_inventory
    ON inventory_count_results (inventory_id)
    WHERE inventory_id IS NOT NULL;
