CREATE TABLE inventory_bulk_operations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookstore_id       BIGINT      NOT NULL,
    created_by_user_id BIGINT      NOT NULL,

    action             VARCHAR(50) NOT NULL,
    selection_type     VARCHAR(20) NOT NULL,

    selected_count     INTEGER     NOT NULL,
    affected_count     INTEGER     NOT NULL,
    skipped_count      INTEGER     NOT NULL,

    parameter_value    VARCHAR(255),
    selection_summary  VARCHAR(1000),

    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_inventory_bulk_operations_bookstore
        FOREIGN KEY (bookstore_id)
            REFERENCES bookstores (id),

    CONSTRAINT fk_inventory_bulk_operations_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id),

    CONSTRAINT ck_inventory_bulk_operations_action
        CHECK (
            action IN (
                       'SET_MINIMUM_STOCK',
                       'ACTIVATE',
                       'DEACTIVATE',
                       'ENABLE_EDITORIAL_PRICE_SYNC',
                       'DISABLE_EDITORIAL_PRICE_SYNC'
                )
            ),

    CONSTRAINT ck_inventory_bulk_operations_selection_type
        CHECK (
            selection_type IN ('IDS', 'FILTER')
            ),

    CONSTRAINT ck_inventory_bulk_operations_counts
        CHECK (
            selected_count >= 0
                AND affected_count >= 0
                AND skipped_count >= 0
                AND affected_count + skipped_count = selected_count
            )
);

CREATE INDEX idx_inventory_bulk_operations_bookstore_created
    ON inventory_bulk_operations (
                                  bookstore_id,
                                  created_at DESC,
                                  id DESC
        );