CREATE TABLE tiendanube_import_analysis_runs
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookstore_id             BIGINT      NOT NULL,
    tiendanube_store_id      BIGINT      NOT NULL,
    store_id                 BIGINT      NOT NULL,
    status                   VARCHAR(30) NOT NULL,
    total_count              INTEGER     NOT NULL DEFAULT 0,
    ready_to_link_count      INTEGER     NOT NULL DEFAULT 0,
    requires_review_count    INTEGER     NOT NULL DEFAULT 0,
    not_in_inventory_count   INTEGER     NOT NULL DEFAULT 0,
    not_in_catalog_count     INTEGER     NOT NULL DEFAULT 0,
    conflict_count           INTEGER     NOT NULL DEFAULT 0,
    already_linked_count     INTEGER     NOT NULL DEFAULT 0,
    resolved_count           INTEGER     NOT NULL DEFAULT 0,
    ignored_count            INTEGER     NOT NULL DEFAULT 0,
    missing_identifier_count INTEGER     NOT NULL DEFAULT 0,
    last_error_type          VARCHAR(100),
    last_error_message       TEXT,
    processing_token         UUID,
    processing_started_at    TIMESTAMPTZ,
    lease_expires_at         TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at             TIMESTAMPTZ,

    CONSTRAINT fk_tiendanube_import_analysis_runs_bookstore
        FOREIGN KEY (bookstore_id) REFERENCES bookstores (id),

    CONSTRAINT fk_tiendanube_import_analysis_runs_store
        FOREIGN KEY (tiendanube_store_id) REFERENCES tiendanube_stores (id),

    CONSTRAINT ck_tiendanube_import_analysis_runs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),

    CONSTRAINT ck_tiendanube_import_analysis_runs_counts
        CHECK (
            total_count >= 0
                AND ready_to_link_count >= 0
                AND requires_review_count >= 0
                AND not_in_inventory_count >= 0
                AND not_in_catalog_count >= 0
                AND conflict_count >= 0
                AND already_linked_count >= 0
                AND resolved_count >= 0
                AND ignored_count >= 0
                AND missing_identifier_count >= 0
            )
);

CREATE UNIQUE INDEX uk_tiendanube_import_analysis_runs_active_store
    ON tiendanube_import_analysis_runs (tiendanube_store_id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE INDEX idx_tiendanube_import_analysis_runs_claim
    ON tiendanube_import_analysis_runs (status, lease_expires_at, created_at, id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE INDEX idx_tiendanube_import_analysis_runs_bookstore
    ON tiendanube_import_analysis_runs (bookstore_id, created_at DESC, id DESC);

CREATE TABLE tiendanube_import_analysis_items
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                 BIGINT      NOT NULL,
    product_id             BIGINT      NOT NULL,
    variant_id             BIGINT      NOT NULL,
    remote_name            TEXT,
    remote_sku             VARCHAR(255),
    remote_barcode         VARCHAR(255),
    remote_isbn            VARCHAR(13),
    identifier_source      VARCHAR(20),
    identifier_recovered   BOOLEAN     NOT NULL DEFAULT FALSE,
    remote_price           NUMERIC(12, 2),
    remote_stock           INTEGER,
    remote_image_url       TEXT,
    remote_published       BOOLEAN,
    status                 VARCHAR(40) NOT NULL,
    match_type             VARCHAR(40) NOT NULL,
    suggested_inventory_id BIGINT,
    suggested_book_id      BIGINT,
    resolved_inventory_id  BIGINT,
    resolution_type        VARCHAR(30),
    message                TEXT,
    resolved_at            TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tiendanube_import_analysis_items_run
        FOREIGN KEY (run_id)
            REFERENCES tiendanube_import_analysis_runs (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_tiendanube_import_analysis_items_suggested_inventory
        FOREIGN KEY (suggested_inventory_id) REFERENCES inventory (id),

    CONSTRAINT fk_tiendanube_import_analysis_items_suggested_book
        FOREIGN KEY (suggested_book_id) REFERENCES books (id),

    CONSTRAINT fk_tiendanube_import_analysis_items_resolved_inventory
        FOREIGN KEY (resolved_inventory_id) REFERENCES inventory (id),

    CONSTRAINT ck_tiendanube_import_analysis_items_identifier_source
        CHECK (identifier_source IS NULL OR identifier_source IN ('BARCODE', 'SKU')),

    CONSTRAINT ck_tiendanube_import_analysis_items_status
        CHECK (status IN (
                          'READY_TO_LINK',
                          'REQUIRES_REVIEW',
                          'NOT_IN_INVENTORY',
                          'NOT_IN_CATALOG',
                          'CONFLICT',
                          'ALREADY_LINKED',
                          'RESOLVED',
                          'IGNORED'
            )),

    CONSTRAINT ck_tiendanube_import_analysis_items_match_type
        CHECK (match_type IN (
                              'EXISTING_LINK',
                              'EXACT_BARCODE',
                              'EXACT_SKU',
                              'INVENTORY_TITLE',
                              'INVENTORY_TITLE_AUTHOR',
                              'INVENTORY_TITLE_PUBLISHER',
                              'CATALOG_MATCH',
                              'FUZZY_TITLE',
                              'MULTIPLE_MATCHES',
                              'NONE'
            )),

    CONSTRAINT ck_tiendanube_import_analysis_items_resolution_type
        CHECK (resolution_type IS NULL OR resolution_type IN ('LINKED', 'IGNORED')),

    CONSTRAINT uk_tiendanube_import_analysis_items_variant
        UNIQUE (run_id, variant_id)
);

CREATE INDEX idx_tiendanube_import_analysis_items_run_status
    ON tiendanube_import_analysis_items (run_id, status, id);

CREATE INDEX idx_tiendanube_import_analysis_items_run_match
    ON tiendanube_import_analysis_items (run_id, match_type, id);

CREATE INDEX idx_tiendanube_import_analysis_items_missing_identifier
    ON tiendanube_import_analysis_items (run_id, id)
    WHERE remote_isbn IS NULL;

CREATE TABLE tiendanube_import_analysis_candidates
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id            BIGINT        NOT NULL,
    inventory_id       BIGINT,
    book_id            BIGINT        NOT NULL,
    rank_order         INTEGER       NOT NULL,
    candidate_source   VARCHAR(20)   NOT NULL,
    match_type         VARCHAR(40)   NOT NULL,
    score              NUMERIC(6, 4) NOT NULL,
    available_for_link BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tiendanube_import_analysis_candidates_item
        FOREIGN KEY (item_id)
            REFERENCES tiendanube_import_analysis_items (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_tiendanube_import_analysis_candidates_inventory
        FOREIGN KEY (inventory_id) REFERENCES inventory (id),

    CONSTRAINT fk_tiendanube_import_analysis_candidates_book
        FOREIGN KEY (book_id) REFERENCES books (id),

    CONSTRAINT ck_tiendanube_import_analysis_candidates_source
        CHECK (candidate_source IN ('INVENTORY', 'CATALOG')),

    CONSTRAINT ck_tiendanube_import_analysis_candidates_match_type
        CHECK (match_type IN (
                              'EXISTING_LINK',
                              'EXACT_BARCODE',
                              'EXACT_SKU',
                              'INVENTORY_TITLE',
                              'INVENTORY_TITLE_AUTHOR',
                              'INVENTORY_TITLE_PUBLISHER',
                              'CATALOG_MATCH',
                              'FUZZY_TITLE',
                              'MULTIPLE_MATCHES',
                              'NONE'
            )),

    CONSTRAINT ck_tiendanube_import_analysis_candidates_rank
        CHECK (rank_order > 0),

    CONSTRAINT ck_tiendanube_import_analysis_candidates_score
        CHECK (score >= 0 AND score <= 1)
);

CREATE UNIQUE INDEX uk_tiendanube_import_analysis_candidates_item_book_inventory
    ON tiendanube_import_analysis_candidates (
                                              item_id,
                                              candidate_source,
                                              book_id,
                                              COALESCE(inventory_id, 0)
        );

CREATE INDEX idx_tiendanube_import_analysis_candidates_item_rank
    ON tiendanube_import_analysis_candidates (item_id, rank_order, id);
