-- =========================================================
-- INVENTORY COST LAYERS
-- =========================================================

CREATE TABLE inventory_cost_layers
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id           BIGINT      NOT NULL,
    quantity_received      INTEGER     NOT NULL,
    quantity_remaining     INTEGER     NOT NULL,
    cost_type              VARCHAR(20) NOT NULL,
    unit_cost              NUMERIC(14, 2),
    discount_percentage    NUMERIC(5, 2),
    reference_price        NUMERIC(14, 2),
    reference_price_source VARCHAR(30),
    source_type            VARCHAR(30) NOT NULL,
    source_movement_id     BIGINT,
    source_reference_id    VARCHAR(100),
    entered_at             TIMESTAMPTZ NOT NULL,
    reversed_at            TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_inventory_cost_layers_inventory
        FOREIGN KEY (inventory_id) REFERENCES inventory (id),

    CONSTRAINT fk_inventory_cost_layers_source_movement
        FOREIGN KEY (source_movement_id) REFERENCES inventory_movements (id),

    CONSTRAINT ck_inventory_cost_layers_quantities
        CHECK (
            quantity_received > 0
                AND quantity_remaining >= 0
                AND quantity_remaining <= quantity_received
            ),

    CONSTRAINT ck_inventory_cost_layers_type
        CHECK (cost_type IN ('REAL', 'ESTIMATED', 'UNKNOWN')),

    CONSTRAINT ck_inventory_cost_layers_cost
        CHECK (
            (cost_type = 'UNKNOWN' AND unit_cost IS NULL)
                OR
            (cost_type IN ('REAL', 'ESTIMATED') AND unit_cost IS NOT NULL AND unit_cost >= 0)
            ),

    CONSTRAINT ck_inventory_cost_layers_discount
        CHECK (
            discount_percentage IS NULL
                OR (discount_percentage >= 0 AND discount_percentage <= 100)
            ),

    CONSTRAINT ck_inventory_cost_layers_reference_price
        CHECK (reference_price IS NULL OR reference_price >= 0),

    CONSTRAINT ck_inventory_cost_layers_reference_source
        CHECK (
            reference_price_source IS NULL
                OR reference_price_source IN ('EDITORIAL_PRICE', 'INVENTORY_SALE_PRICE')
            ),

    CONSTRAINT ck_inventory_cost_layers_source_type
        CHECK (
            source_type IN (
                            'LEGACY_INVENTORY',
                            'OPENING_INVENTORY',
                            'PURCHASE',
                            'STOCK_ENTRY',
                            'ADJUSTMENT',
                            'RETURN',
                            'UNTRACKED'
                )
            ),

    CONSTRAINT ck_inventory_cost_layers_reversal
        CHECK (reversed_at IS NULL OR quantity_remaining = 0)
);

CREATE INDEX idx_inventory_cost_layers_inventory_fifo
    ON inventory_cost_layers (inventory_id, entered_at, id)
    WHERE reversed_at IS NULL AND quantity_remaining > 0;

CREATE INDEX idx_inventory_cost_layers_inventory_cost_type
    ON inventory_cost_layers (inventory_id, cost_type)
    WHERE reversed_at IS NULL;

CREATE INDEX idx_inventory_cost_layers_pending_cost
    ON inventory_cost_layers (inventory_id, id)
    WHERE reversed_at IS NULL AND unit_cost IS NULL;

CREATE UNIQUE INDEX uk_inventory_cost_layers_source_movement
    ON inventory_cost_layers (source_movement_id)
    WHERE source_movement_id IS NOT NULL;

-- =========================================================
-- COST ALLOCATIONS
-- =========================================================

CREATE TABLE inventory_cost_allocations
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_layer_id           BIGINT      NOT NULL,
    inventory_movement_id   BIGINT      NOT NULL,
    quantity                INTEGER     NOT NULL,
    reversed_at             TIMESTAMPTZ,
    reversed_by_movement_id BIGINT,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_inventory_cost_allocations_layer
        FOREIGN KEY (cost_layer_id) REFERENCES inventory_cost_layers (id),

    CONSTRAINT fk_inventory_cost_allocations_movement
        FOREIGN KEY (inventory_movement_id) REFERENCES inventory_movements (id),

    CONSTRAINT fk_inventory_cost_allocations_reversal_movement
        FOREIGN KEY (reversed_by_movement_id) REFERENCES inventory_movements (id),

    CONSTRAINT uk_inventory_cost_allocations_layer_movement
        UNIQUE (cost_layer_id, inventory_movement_id),

    CONSTRAINT ck_inventory_cost_allocations_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_inventory_cost_allocations_reversal
        CHECK (reversed_by_movement_id IS NULL OR reversed_at IS NOT NULL)
);

CREATE INDEX idx_inventory_cost_allocations_movement
    ON inventory_cost_allocations (inventory_movement_id, id);

CREATE INDEX idx_inventory_cost_allocations_active_layer
    ON inventory_cost_allocations (cost_layer_id, id)
    WHERE reversed_at IS NULL;

-- =========================================================
-- EXISTING INVENTORY BECOMES THE ECONOMIC OPENING BASELINE
-- No historical cost or discount is invented.
-- =========================================================

INSERT INTO inventory_cost_layers (inventory_id,
                                   quantity_received,
                                   quantity_remaining,
                                   cost_type,
                                   unit_cost,
                                   discount_percentage,
                                   reference_price,
                                   reference_price_source,
                                   source_type,
                                   source_movement_id,
                                   source_reference_id,
                                   entered_at,
                                   reversed_at,
                                   created_at,
                                   updated_at)
SELECT inventory.id,
       inventory.stock,
       inventory.stock,
       'UNKNOWN',
       NULL,
       NULL,
       COALESCE(effective_price.price, inventory.sale_price),
       CASE
           WHEN effective_price.price IS NOT NULL THEN 'EDITORIAL_PRICE'
           WHEN inventory.sale_price IS NOT NULL THEN 'INVENTORY_SALE_PRICE'
           ELSE NULL
           END,
       'LEGACY_INVENTORY',
       NULL,
       inventory.id::TEXT,
       COALESCE(inventory.created_at, CURRENT_TIMESTAMP),
       NULL,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM inventory
         LEFT JOIN LATERAL (
    SELECT price.price
    FROM effective_editorial_prices price
    WHERE price.book_id = inventory.book_id
      AND price.active = TRUE
    ORDER BY price.valid_from DESC, price.id DESC
    LIMIT 1
    ) effective_price ON TRUE
WHERE inventory.stock > 0;
